// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using URLShorteningApi.Models;

#nullable disable

namespace URLShortening.Migrations
{
    [DbContext(typeof(URLShorteningContext))]
    [Migration("20250923084706_AddAccessCountToURLShorteningItem")]
    partial class AddAccessCountToURLShorteningItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("URLShorteningApi.Models.URLShorteningItem", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<int>("accessCount")
                        .HasColumnType("integer");

                    b.Property<string>("createdAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("shortCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("updatedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("URLShorteningItems");
                });
#pragma warning restore 612, 618
        }
    }
}
